/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { CNPJ } from './models/CNPJ';
export type { CobApresentacao } from './models/CobApresentacao';
export type { CobBase } from './models/CobBase';
export type { CobBaseCopiaCola } from './models/CobBaseCopiaCola';
export type { CobCompleta } from './models/CobCompleta';
export type { CobCriacao } from './models/CobCriacao';
export type { CobDataDeVencimento } from './models/CobDataDeVencimento';
export type { CobExpiracao } from './models/CobExpiracao';
export type { CobGerada } from './models/CobGerada';
export type { CobPayload } from './models/CobPayload';
export { CobPayloadValor } from './models/CobPayloadValor';
export { CobrancaStatus } from './models/CobrancaStatus';
export { CobRAtualizacao } from './models/CobRAtualizacao';
export type { CobRBase } from './models/CobRBase';
export type { CobRCompleta } from './models/CobRCompleta';
export { CobRConfiguracao } from './models/CobRConfiguracao';
export { CobRevisada } from './models/CobRevisada';
export type { CobRGerada } from './models/CobRGerada';
export type { CobRNotification } from './models/CobRNotification';
export type { CobRRevisada } from './models/CobRRevisada';
export type { CobRSolicitada } from './models/CobRSolicitada';
export { CobRStatus } from './models/CobRStatus';
export { CobRStatusRevisada } from './models/CobRStatusRevisada';
export type { CobRTentativas } from './models/CobRTentativas';
export type { CobsConsultadas } from './models/CobsConsultadas';
export type { CobSolicitada } from './models/CobSolicitada';
export type { CobsRConsultadas } from './models/CobsRConsultadas';
export type { CobsVConsultadas } from './models/CobsVConsultadas';
export { CobValor } from './models/CobValor';
export type { CobVCompleta } from './models/CobVCompleta';
export type { CobVGerada } from './models/CobVGerada';
export type { CobVPayload } from './models/CobVPayload';
export type { CobVPayloadValor } from './models/CobVPayloadValor';
export { CobVRevisada } from './models/CobVRevisada';
export type { CobVSolicitada } from './models/CobVSolicitada';
export type { CobVValor } from './models/CobVValor';
export type { CPF } from './models/CPF';
export type { DadosBancarios } from './models/DadosBancarios';
export { DadosBancariosRecebedor } from './models/DadosBancariosRecebedor';
export type { DadosComplementaresPessoa } from './models/DadosComplementaresPessoa';
export type { DadosDevedor } from './models/DadosDevedor';
export type { DadosDevedorRecorrencia } from './models/DadosDevedorRecorrencia';
export type { DadosPagadorRec } from './models/DadosPagadorRec';
export type { DadosRecebedor } from './models/DadosRecebedor';
export { Devolucao } from './models/Devolucao';
export type { DevolucaoId } from './models/DevolucaoId';
export { DevolucaoNatureza } from './models/DevolucaoNatureza';
export { DevolucaoNaturezaPixAutomatico } from './models/DevolucaoNaturezaPixAutomatico';
export { DevolucaoPixAutomatico } from './models/DevolucaoPixAutomatico';
export type { DevolucaoSolicitada } from './models/DevolucaoSolicitada';
export { DevolucaoSolicitadaNatureza } from './models/DevolucaoSolicitadaNatureza';
export type { EndToEndId } from './models/EndToEndId';
export type { Fim } from './models/Fim';
export type { InfoBaseAgenciaConta } from './models/InfoBaseAgenciaConta';
export { InfoBaseChave } from './models/InfoBaseChave';
export type { Inicio } from './models/Inicio';
export type { itensPorPagina } from './models/itensPorPagina';
export type { LoteCobVConsultado } from './models/LoteCobVConsultado';
export type { LoteCobVGerado } from './models/LoteCobVGerado';
export type { LotesCobVConsultados } from './models/LotesCobVConsultados';
export type { paginaAtual } from './models/paginaAtual';
export type { Paginacao } from './models/Paginacao';
export type { ParametrosConsultaCob } from './models/ParametrosConsultaCob';
export type { ParametrosConsultaCobR } from './models/ParametrosConsultaCobR';
export type { ParametrosConsultaLote } from './models/ParametrosConsultaLote';
export { ParametrosConsultaPayloadLocation } from './models/ParametrosConsultaPayloadLocation';
export type { ParametrosConsultaPayloadLocationRec } from './models/ParametrosConsultaPayloadLocationRec';
export type { ParametrosConsultaPix } from './models/ParametrosConsultaPix';
export type { ParametrosConsultaRec } from './models/ParametrosConsultaRec';
export type { ParametrosConsultaWebhooks } from './models/ParametrosConsultaWebhooks';
export { PayloadLocation } from './models/PayloadLocation';
export type { PayloadLocationCob } from './models/PayloadLocationCob';
export { PayloadLocationCompleta } from './models/PayloadLocationCompleta';
export type { PayloadLocationConsultadas } from './models/PayloadLocationConsultadas';
export type { PayloadLocationId } from './models/PayloadLocationId';
export type { PayloadLocationRecCompleta } from './models/PayloadLocationRecCompleta';
export type { PayloadLocationRecConsultadas } from './models/PayloadLocationRecConsultadas';
export type { PayloadLocationRecGerada } from './models/PayloadLocationRecGerada';
export type { PayloadLocationRecId } from './models/PayloadLocationRecId';
export { PayloadLocationRecSolicitada } from './models/PayloadLocationRecSolicitada';
export { PayloadLocationSolicitada } from './models/PayloadLocationSolicitada';
export type { PessoaFisica } from './models/PessoaFisica';
export type { PessoaFisicaRecorrencia } from './models/PessoaFisicaRecorrencia';
export type { PessoaJuridica } from './models/PessoaJuridica';
export type { PessoaJuridicaRecorrencia } from './models/PessoaJuridicaRecorrencia';
export type { Pix } from './models/Pix';
export type { PixAutomatico } from './models/PixAutomatico';
export type { PixConsultados } from './models/PixConsultados';
export type { PixValorAbatimento } from './models/PixValorAbatimento';
export type { PixValorDesconto } from './models/PixValorDesconto';
export type { PixValorJuros } from './models/PixValorJuros';
export type { PixValorMulta } from './models/PixValorMulta';
export type { PixValorOriginal } from './models/PixValorOriginal';
export { PixValorSaque } from './models/PixValorSaque';
export { PixValorTroco } from './models/PixValorTroco';
export type { Problema } from './models/Problema';
export { RecAtivacao } from './models/RecAtivacao';
export type { RecAtivacaoSolicitada } from './models/RecAtivacaoSolicitada';
export type { RecAtualizacao } from './models/RecAtualizacao';
export { RecBase } from './models/RecBase';
export { RecCompleta } from './models/RecCompleta';
export type { RecCompletaPesquisada } from './models/RecCompletaPesquisada';
export { RecConfiguracao } from './models/RecConfiguracao';
export { RecEncerramento } from './models/RecEncerramento';
export type { RecGerada } from './models/RecGerada';
export type { RecId } from './models/RecId';
export type { RecNotification } from './models/RecNotification';
export type { RecPayload } from './models/RecPayload';
export { RecRevisada } from './models/RecRevisada';
export type { RecsConsultadas } from './models/RecsConsultadas';
export type { RecSolicitada } from './models/RecSolicitada';
export { RecStatus } from './models/RecStatus';
export type { Revisao } from './models/Revisao';
export type { SolicRecAtualizacao } from './models/SolicRecAtualizacao';
export type { SolicRecBase } from './models/SolicRecBase';
export type { SolicRecCompleta } from './models/SolicRecCompleta';
export type { SolicRecId } from './models/SolicRecId';
export { SolicRecRevisada } from './models/SolicRecRevisada';
export type { SolicRecSolicitada } from './models/SolicRecSolicitada';
export { SolicRecStatus } from './models/SolicRecStatus';
export type { TxId } from './models/TxId';
export type { Violacao } from './models/Violacao';
export type { WebhookCobRCompleto } from './models/WebhookCobRCompleto';
export type { WebhookCobRSolicitado } from './models/WebhookCobRSolicitado';
export type { WebhookCompleto } from './models/WebhookCompleto';
export type { WebhookRecBase } from './models/WebhookRecBase';
export type { WebhookRecCompleto } from './models/WebhookRecCompleto';
export type { WebhookRecSolicitado } from './models/WebhookRecSolicitado';
export type { WebhooksConsultados } from './models/WebhooksConsultados';
export type { WebhookSolicitado } from './models/WebhookSolicitado';
export type { WebhooksRecConsultados } from './models/WebhooksRecConsultados';

export { CobService } from './services/CobService';
export { CobPayloadService } from './services/CobPayloadService';
export { CobRService } from './services/CobRService';
export { CobVService } from './services/CobVService';
export { LoteCobVService } from './services/LoteCobVService';
export { PayloadLocationService } from './services/PayloadLocationService';
export { PayloadLocationRecService } from './services/PayloadLocationRecService';
export { PixService } from './services/PixService';
export { RecService } from './services/RecService';
export { RecPayloadService } from './services/RecPayloadService';
export { SolicRecService } from './services/SolicRecService';
export { WebhookService } from './services/WebhookService';
export { WebhookCobRService } from './services/WebhookCobRService';
export { WebhookRecService } from './services/WebhookRecService';
